### ISSUE TITLE
API gateway integration

### ISSUE THREAD

**Issue by mehulsuresh** [aws-samples/amazon-lex-skype-integration#1]
Hey could you clearly explain how to connect and setup the API gateway. I couldn't get it to work. 
i keep getting this error 
Unexpected token u in JSON at position 0 at Object.parse (native) at handler (/var/task/index.js:62:24)

**Comment by kbash09** [comment]
It seems like the API Gateway you created is not passing on the request body to the Lambda function. Make sure you have `Use Lambda Proxy Integration` checked when you create the API Gateway. I have updated the README to make this clear (see step #7 in the README.

**Comment by mehulsuresh** [comment]
Hey @filanthropic thanks for the quick reply!

I set up a post method with Lambda Proxy integration enabled and now the lambda function gets the message and processes the output. 
 But how do i get it to send the message back to Skype at the moment it just times out after 3 seconds.

**Comment by mehulsuresh** [comment]
Never mind I fixed it. Just had to increase the timeout in the lambda function. 👍
